In [8]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [14]:
import time 
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print c
print("Vectorized version : " + str(1000*(toc - tic)) + "ms")


c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print c
print("For loop : " + str(1000*(toc-tic)) + "ms")

250023.96249547927
Vectorized version : 3.43608856201ms
250023.96249548232
For loop : 842.555046082ms


In [16]:
A = np.array([[56.0,0.0,4.4,68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])


In [17]:
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [29]:
c = A.sum(axis = 0)
print c

[ 59.  239.  155.4  76.9]


In [31]:
percentage = 100 * A/c.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [32]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)

In [35]:
np.shape(B)


(4, 1)